-- AlterTable
ALTER TABLE "Admin" ALTER COLUMN "AdminOtp" SET DEFAULT '0',
ALTER COLUMN "AdminOtp" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "userOtp" SET DEFAULT '0',
ALTER COLUMN "userOtp" SET DATA TYPE TEXT;
